### ISSUE TITLE
Precedence in Includes and excludes

### ISSUE THREAD

**Issue by manuGil** [ITC-CRIB/fairly#56]
To include and exclude files from a dataset we are using the following operations:

```python

local = fairly.dataset("./test-dataset/mydataset/")

# to include:
local.includes.append("*.jpg")
# to exclude:
local.excludes.append("*.jpg")
# then we save changes to manifest.yaml
local.save()
````

The above results in the following in `manifest.yaml`:

```yml
files:
  includes:
  - ARP1_.info
  - ARP1_d01.zip
  - my_code.py
  - Survey_AI.csv
  - '*.jpg'
  excludes:
  - '*.jpg'
 ```

**How fairly mange the precedence of this case?** It is based on the order in the file? or have *excludes* precedence over *includes*?
